"""Init

Revision ID: 8e7d479f5622
Revises: 
Create Date: 2024-11-10 16:16:05.227981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7d479f5622'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numbers_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_numbers_choices_id'), 'numbers_choices', ['id'], unique=False)
    op.create_index(op.f('ix_numbers_choices_number'), 'numbers_choices', ['number'], unique=False)
    op.create_table('time_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_range', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_ranges_id'), 'time_ranges', ['id'], unique=False)
    op.create_index(op.f('ix_time_ranges_name'), 'time_ranges', ['name'], unique=True)
    op.create_index(op.f('ix_time_ranges_time_range'), 'time_ranges', ['time_range'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('number_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number_choice_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['number_choice_id'], ['numbers_choices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_number_selections_id'), 'number_selections', ['id'], unique=False)
    op.create_table('time_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(), nullable=True),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.Column('time_range_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['time_range_id'], ['time_ranges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_choices_choice'), 'time_choices', ['choice'], unique=False)
    op.create_index(op.f('ix_time_choices_id'), 'time_choices', ['id'], unique=False)
    op.create_table('time_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_choice_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['time_choice_id'], ['time_choices.id'], name='fk_time_selection_time_choice'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_selections_id'), 'time_selections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_selections_id'), table_name='time_selections')
    op.drop_table('time_selections')
    op.drop_index(op.f('ix_time_choices_id'), table_name='time_choices')
    op.drop_index(op.f('ix_time_choices_choice'), table_name='time_choices')
    op.drop_table('time_choices')
    op.drop_index(op.f('ix_number_selections_id'), table_name='number_selections')
    op.drop_table('number_selections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_time_ranges_time_range'), table_name='time_ranges')
    op.drop_index(op.f('ix_time_ranges_name'), table_name='time_ranges')
    op.drop_index(op.f('ix_time_ranges_id'), table_name='time_ranges')
    op.drop_table('time_ranges')
    op.drop_index(op.f('ix_numbers_choices_number'), table_name='numbers_choices')
    op.drop_index(op.f('ix_numbers_choices_id'), table_name='numbers_choices')
    op.drop_table('numbers_choices')
    # ### end Alembic commands ###
